Repository Porchetta-Industries/CrackMapExec, pull requests merged in 2021-12, with the labels that each got.

#505 Fix winrm login failed
  cme/protocols/winrm.py
Labels: bug

#514 Fix a number of unhandled expections in cme/protocols/smb.py
  cme/protocols/smb.py
Labels: enhancement

#512 Add drop_searchConnector-ms module
  cme/modules/drop_searchConnector-ms.py
Labels: module
