Repository Porchetta-Industries/CrackMapExec, pull requests merged in 2022-06, with the labels that each got.

#580 Switch to poetry-core
  pyproject.toml
Labels: awesome sauce!, dank

#581 Use beautifulsoup4 instead of bs4
  pyproject.toml
Labels: dank

#574 accept pywerview 0.4.0
  pyproject.toml
Labels: enhancement

#552 Added module for finding other network addresses on a host via WMI
  cme/modules/get_netconnections.py
Labels: enhancement, dank

#570 Add -codec execution option
  cme/protocols/smb.py
  cme/protocols/smb/atexec.py
  cme/protocols/smb/mmcexec.py
  cme/protocols/smb/smbexec.py
  cme/protocols/smb/wmiexec.py
Labels: enhancement

#561 Stop crackmapexec crashing from concurrency-issues (tested with SMB-mode)
  cme/crackmapexec.py
Labels: enhancement, dank

#559 Add SSL support to winrm protocol
  cme/protocols/winrm.py
Labels: enhancement, dank

#572 :rocket: add support for filter user when searching for loggedon
  cme/protocols/smb.py
Labels: enhancement

#578 NanoDump Bugfixes
  cme/protocols/winrm.py
Labels: enhancement

#538 Fixed improper exception handling of lsass dump parsing
  cme/modules/lsassy_dump.py
Labels: moar info required comrade

#545 Add smbv1 and signing into sqlite database
  cme/protocols/smb.py
  cme/protocols/smb/database.py
  cme/protocols/smb/db_navigator.py
Labels: enhancement

#573 Nix Support
  flake.lock
  flake.nix
  shell.nix
Labels: enhancement, help wanted

#569 Added Termux support
  cme/first_run.py
Labels: help wanted
