Repository Porchetta-Industries/CrackMapExec, pull requests merged in 2022-10, with the labels that each got.

#597 Mssql upload / download
  cme/modules/nanodump.py
  cme/protocols/mssql.py
  cme/protocols/mssql/database.py
  cme/protocols/mssql/mssqlexec.py
Labels: module, all good

#610 Add the new daclread.py LDAP module and the msada_guids.py library
  cme/helpers/msada_guids.py
  cme/modules/daclread.py
Labels: module, all good

#636 Add KeePass discovery module
  cme/modules/keepass_discover.py
Labels: module, all good

#643 Improved cmedb export function
  cme/cmedb.py
  cme/protocols/smb/database.py
Labels: enhancement, all good

#640 Module to check for NTLMv1 Compatibility
  cme/modules/ntlmv1.py
Labels: enhancement, all good

#646 Module to check for AlwaysInstallElevated
  cme/modules/install_elevated.py
Labels: module, dank, all good

#647 Added functionality to retrieve ssoauthookie from Microsoft Teams local db
  cme/modules/teams_localdb.py
Labels: module, dank, in review

#614 Add GMSA module
  cme/protocols/ldap.py
  cme/protocols/ldap/gmsa.py
Labels: module, all good

#653 Add Masky module
  cme/modules/masky.py
  pyproject.toml
Labels: awesome sauce!, module, dank, all good

#655 Fix kerberos authentication
  cme/cli.py
  cme/connection.py
  cme/protocols/ldap.py
  cme/protocols/mssql.py
  cme/protocols/smb.py
Labels: enhancement, awesome sauce!, all good
