Repository Porchetta-Industries/CrackMapExec, pull requests merged in 2022-09, with the labels that each got.

#613 whoami LDAP module
  cme/modules/whoami.py
Labels: module, in review

#641 Fix logging with LDAPS protocol
  cme/protocols/ldap.py
Labels: enhancement

#638 Cmedb export shares
  cme/cmedb.py
Labels: enhancement, in review

#639 FTP Protocol Addition
  cme/protocols/ftp.py
  cme/protocols/ftp/__init__.py
  cme/protocols/ftp/database.py
  cme/protocols/ftp/db_navigator.py
Labels: enhancement, all good
